#!/usr/bin/env python3
"""Materialize the frozen six-producer ictal scale and fold-ID probes.

The command accepts only paths plus independently pinned artifact identities.
All score grids, masks, fold labels, and statistics are regenerated by opaque
strict loaders; callers cannot supply probe features, predictions, or labels.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import re
import sys
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.derive_tusz_ictal_oof_fold_manifests import (  # noqa: E402
    load_bound_deepsoz_registry,
)
from scripts.materialize_tusz_ictal_token_cache import (  # noqa: E402
    load_formal_token_corpus,
)
from src.soz.concept_oof import load_ictal_concept_oof_protocol  # noqa: E402
from src.soz.data.deepsoz_target_v2 import (  # noqa: E402
    load_verified_deepsoz_target_v2_artifact,
)
from src.soz.data.public_ledger_builder import (  # noqa: E402
    load_tusz_deepsoz_public_ledger_build,
)
from src.soz.formal_reasoner_pipeline import (  # noqa: E402
    build_verified_global_timeline_context,
)
from src.soz.ictal_native_eval import (  # noqa: E402
    load_bound_deepsoz_signal_preflight_artifact,
    load_ictal_native_eval_manifest,
    load_ictal_native_eval_token_corpus,
)
from src.soz.ictal_prediction_artifacts import (  # noqa: E402
    load_ictal_fold_identity_probe_artifact,
    load_ictal_scale_probe_artifact,
    materialize_ictal_fold_identity_probe_artifact,
    materialize_ictal_scale_probe_artifact,
)
from src.soz.ictal_production import load_ictal_production_run  # noqa: E402
from src.soz.preprocessing_parity import (  # noqa: E402
    load_preprocessing_selection_capability,
)


_SHA256_RE = re.compile(r"[0-9a-f]{64}")
_SELECTIONS = ("fold0", "fold1", "fold2", "fold3", "fold4", "final")


def _existing_bundle_digests(path: Path) -> tuple[str, str] | None:
    """Return output digests only when a complete prior probe bundle exists.

    The strict loader below still regenerates the probe grid and verifies the
    complete bundle.  This merely makes the two-probe CLI safely resumable when
    the scale probe was atomically published before fold-ID generation failed.
    """

    manifest = path / "manifest.json"
    receipt = path / "receipt.json"
    if not path.exists():
        return None
    if not path.is_dir() or not manifest.is_file() or not receipt.is_file():
        raise ValueError(f"Incomplete existing probe output cannot be resumed: {path}")
    return (
        hashlib.sha256(manifest.read_bytes()).hexdigest(),
        hashlib.sha256(receipt.read_bytes()).hexdigest(),
    )


def _sha256(value: str) -> str:
    normalized = str(value).strip()
    if not _SHA256_RE.fullmatch(normalized):
        raise argparse.ArgumentTypeError("expected a lowercase SHA-256 digest")
    return normalized


def _production_run_spec(value: str) -> tuple[str, Path, str]:
    fields = value.split("=", 2)
    if len(fields) != 3:
        raise argparse.ArgumentTypeError(
            "production run must use SELECTION=PATH=MANIFEST_SHA256"
        )
    selection, raw_path, raw_sha = fields
    if selection not in _SELECTIONS:
        raise argparse.ArgumentTypeError(f"unknown producer selection: {selection}")
    if not raw_path:
        raise argparse.ArgumentTypeError("production run path cannot be empty")
    return selection, Path(raw_path), _sha256(raw_sha)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Strictly replay six formal ictal producers and publish the "
            "target-free source-dev scale and source-train OOF fold-ID probes"
        )
    )
    parser.add_argument(
        "--production-run",
        action="append",
        type=_production_run_spec,
        required=True,
        help="repeat six times as SELECTION=PATH=MANIFEST_SHA256",
    )
    parser.add_argument("--target-v2-directory", type=Path, required=True)
    parser.add_argument("--deepsoz-source-csv", type=Path, required=True)
    parser.add_argument("--deepsoz-split-csv", type=Path, required=True)
    parser.add_argument(
        "--expected-target-v2-target-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-target-v2-summary-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-target-v2-readme-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-deepsoz-source-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-deepsoz-split-sha256", type=_sha256, required=True
    )
    parser.add_argument("--public-ledger", type=Path, required=True)
    parser.add_argument(
        "--expected-public-ledger-bundle-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-public-ledger-build-sha256", type=_sha256, required=True
    )
    parser.add_argument("--oof-protocol", type=Path, required=True)
    parser.add_argument(
        "--expected-oof-protocol-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-oof-protocol-receipt-sha256", type=_sha256, required=True
    )
    parser.add_argument("--signal-preflight-bundle", type=Path, required=True)
    parser.add_argument(
        "--expected-signal-preflight-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-signal-preflight-receipt-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--preprocessing-selection-bundle", type=Path, required=True
    )
    parser.add_argument(
        "--expected-preprocessing-selection-artifact-sha256",
        type=_sha256,
        required=True,
    )
    parser.add_argument(
        "--expected-preprocessing-protocol-receipt-sha256",
        type=_sha256,
        required=True,
    )
    parser.add_argument("--source-train-token-corpus", type=Path, required=True)
    parser.add_argument(
        "--expected-source-train-token-index-sha256", type=_sha256, required=True
    )
    parser.add_argument("--source-dev-manifest-bundle", type=Path, required=True)
    parser.add_argument(
        "--expected-source-dev-manifest-artifact-sha256", type=_sha256, required=True
    )
    parser.add_argument(
        "--expected-source-dev-manifest-receipt-sha256", type=_sha256, required=True
    )
    parser.add_argument("--source-dev-token-corpus", type=Path, required=True)
    parser.add_argument(
        "--expected-source-dev-token-index-sha256", type=_sha256, required=True
    )
    parser.add_argument("--edf-root", type=Path, required=True)
    parser.add_argument("--scale-output-directory", type=Path, required=True)
    parser.add_argument("--fold-id-output-directory", type=Path, required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    specs = tuple(args.production_run)
    if len(specs) != len(_SELECTIONS):
        raise ValueError("Exactly six formal production runs are required")
    by_selection = {selection: (path, digest) for selection, path, digest in specs}
    if len(by_selection) != len(_SELECTIONS) or tuple(sorted(by_selection)) != tuple(
        sorted(_SELECTIONS)
    ):
        raise ValueError("Production runs must contain each fold0-fold4 and final once")
    production_runs = tuple(
        load_ictal_production_run(
            by_selection[selection][0],
            expected_manifest_sha256=by_selection[selection][1],
        )
        for selection in _SELECTIONS
    )
    if tuple(str(run.manifest["selection"]) for run in production_runs) != _SELECTIONS:
        raise ValueError("Loaded production-run selections disagree with their specs")

    target = load_verified_deepsoz_target_v2_artifact(
        args.target_v2_directory,
        args.deepsoz_source_csv,
        args.deepsoz_split_csv,
        expected_target_artifact_sha256=(
            args.expected_target_v2_target_artifact_sha256
        ),
        expected_summary_artifact_sha256=(
            args.expected_target_v2_summary_artifact_sha256
        ),
        expected_readme_artifact_sha256=(
            args.expected_target_v2_readme_artifact_sha256
        ),
        expected_source_input_sha256=args.expected_deepsoz_source_sha256,
        expected_split_input_sha256=args.expected_deepsoz_split_sha256,
    )
    signal = load_bound_deepsoz_signal_preflight_artifact(
        args.signal_preflight_bundle,
        expected_artifact_sha256=args.expected_signal_preflight_artifact_sha256,
        expected_receipt_sha256=args.expected_signal_preflight_receipt_sha256,
    )
    timeline = build_verified_global_timeline_context(target, signal)

    registry, _ = load_bound_deepsoz_registry(
        args.deepsoz_source_csv,
        args.deepsoz_split_csv,
        expected_source_sha256=args.expected_deepsoz_source_sha256,
        expected_split_sha256=args.expected_deepsoz_split_sha256,
    )
    public_ledger = load_tusz_deepsoz_public_ledger_build(
        args.public_ledger,
        expected_bundle_sha256=args.expected_public_ledger_bundle_sha256,
        expected_build_sha256=args.expected_public_ledger_build_sha256,
    )
    oof_protocol = load_ictal_concept_oof_protocol(
        args.oof_protocol,
        registry,
        public_ledger,
        expected_artifact_sha256=args.expected_oof_protocol_artifact_sha256,
        expected_protocol_sha256=args.expected_oof_protocol_receipt_sha256,
    )
    preprocessing = load_preprocessing_selection_capability(
        args.preprocessing_selection_bundle,
        expected_artifact_sha256=(
            args.expected_preprocessing_selection_artifact_sha256
        ),
        expected_protocol_receipt_sha256=(
            args.expected_preprocessing_protocol_receipt_sha256
        ),
    )
    source_train = load_formal_token_corpus(
        args.source_train_token_corpus,
        expected_index_sha256=args.expected_source_train_token_index_sha256,
        preprocessing_selection=preprocessing,
    )
    source_dev_manifest = load_ictal_native_eval_manifest(
        args.source_dev_manifest_bundle,
        signal,
        args.edf_root,
        expected_artifact_sha256=args.expected_source_dev_manifest_artifact_sha256,
        expected_receipt_sha256=args.expected_source_dev_manifest_receipt_sha256,
        expected_signal_artifact_sha256=(
            args.expected_signal_preflight_artifact_sha256
        ),
        expected_signal_receipt_sha256=(
            args.expected_signal_preflight_receipt_sha256
        ),
    )
    source_dev = load_ictal_native_eval_token_corpus(
        args.source_dev_token_corpus,
        source_dev_manifest,
        expected_index_sha256=args.expected_source_dev_token_index_sha256,
        expected_manifest_artifact_sha256=(
            args.expected_source_dev_manifest_artifact_sha256
        ),
        expected_manifest_receipt_sha256=(
            args.expected_source_dev_manifest_receipt_sha256
        ),
        expected_signal_artifact_sha256=(
            args.expected_signal_preflight_artifact_sha256
        ),
        expected_signal_receipt_sha256=(
            args.expected_signal_preflight_receipt_sha256
        ),
    )

    scale_digests = _existing_bundle_digests(args.scale_output_directory)
    if scale_digests is None:
        scale = materialize_ictal_scale_probe_artifact(
            production_runs=production_runs,
            oof_protocol=oof_protocol,
            timeline_context=timeline,
            source_dev_corpus=source_dev,
            output_directory=args.scale_output_directory,
        )
    else:
        scale = load_ictal_scale_probe_artifact(
            args.scale_output_directory,
            production_runs=production_runs,
            oof_protocol=oof_protocol,
            timeline_context=timeline,
            source_dev_corpus=source_dev,
            expected_artifact_sha256=scale_digests[0],
            expected_receipt_sha256=scale_digests[1],
        )

    fold_digests = _existing_bundle_digests(args.fold_id_output_directory)
    if fold_digests is None:
        fold_id = materialize_ictal_fold_identity_probe_artifact(
            production_runs=production_runs,
            oof_protocol=oof_protocol,
            timeline_context=timeline,
            source_train_corpus=source_train,
            output_directory=args.fold_id_output_directory,
        )
    else:
        fold_id = load_ictal_fold_identity_probe_artifact(
            args.fold_id_output_directory,
            production_runs=production_runs,
            oof_protocol=oof_protocol,
            timeline_context=timeline,
            source_train_corpus=source_train,
            expected_artifact_sha256=fold_digests[0],
            expected_receipt_sha256=fold_digests[1],
        )
    print(
        json.dumps(
            {
                "fold_identity_metrics": asdict(fold_id.receipt),
                "fold_id_artifact_sha256": fold_id.artifact_sha256,
                "fold_id_bundle_receipt_sha256": fold_id.bundle_receipt_sha256,
                "fold_identity_receipt_sha256": (
                    fold_id.fold_identity_receipt_sha256
                ),
                "scale_alignment_receipt_sha256": (
                    scale.scale_alignment_receipt_sha256
                ),
                "scale_alignment_metrics": {
                    **asdict(scale.receipt),
                    "maximum_pairwise_quantile_gap": (
                        scale.receipt.maximum_pairwise_quantile_gap
                    ),
                },
                "scale_artifact_sha256": scale.artifact_sha256,
                "scale_bundle_receipt_sha256": scale.bundle_receipt_sha256,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
