#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SESSION_NAME="${SESSION_NAME:-cbratfm_hardbg_targeted_seed2051_smoke}"
OUTPUT_BASE="${OUTPUT_BASE:-outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_cbratfm_hardbg_target_temporal_smoke10_seed2051}"
WAIT_SESSIONS="${WAIT_SESSIONS:-cbratfm_rows119_queued,cbramod_rows119_remaining_after_cbratfm,cbratfm_hardbg_seed2050_smoke}"

SEEDS="${SEEDS:-2051}"
MAX_PATIENTS="${MAX_PATIENTS:-10}"
TOKENIZER_EPOCHS="${TOKENIZER_EPOCHS:-4}"
CLASSIFIER_EPOCHS="${CLASSIFIER_EPOCHS:-12}"
DEVICE="${DEVICE:-cuda}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"

REGION_HARD_BACKGROUND_TARGET_WEIGHT="${REGION_HARD_BACKGROUND_TARGET_WEIGHT:-0.05}"
REGION_HARD_BACKGROUND_TARGET_REGIONS="${REGION_HARD_BACKGROUND_TARGET_REGIONS:-right_temporal,left_temporal}"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo "Session already exists: $SESSION_NAME"
  exit 0
fi

mkdir -p "$REPO_ROOT/$OUTPUT_BASE"

cat > "$REPO_ROOT/$OUTPUT_BASE/queued_command.txt" <<EOF
SESSION_NAME=$SESSION_NAME
WAIT_SESSIONS=$WAIT_SESSIONS
OUTPUT_BASE=$OUTPUT_BASE
SEEDS=$SEEDS
MAX_PATIENTS=$MAX_PATIENTS
TOKENIZER_EPOCHS=$TOKENIZER_EPOCHS
CLASSIFIER_EPOCHS=$CLASSIFIER_EPOCHS
REGION_HARD_BACKGROUND_TARGET_WEIGHT=$REGION_HARD_BACKGROUND_TARGET_WEIGHT
REGION_HARD_BACKGROUND_TARGET_REGIONS=$REGION_HARD_BACKGROUND_TARGET_REGIONS
TEACHER_CACHE_DIR=outputs/tfm_soz/private_0622_fix_rows119_teacher_logits_tfm_2028_2029_2030_smoke10
TEACHER_DISTILL_REGION_WEIGHT=0.25
TEACHER_DISTILL_CHANNEL_WEIGHT=0.05
DISABLE_REGION_BIAS_CALIBRATION=1
BACKGROUND_NEGATIVE_DIR=outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives
BACKGROUND_NEGATIVE_RATIO=0.75
BACKGROUND_NEGATIVE_SAMPLING_MODE=cluster_balanced
VALIDATION_BACKGROUND_NEGATIVE_DIR=outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives
VALIDATION_BACKGROUND_SELECTION_WEIGHT=0.75
SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT=0.10
CHANNEL_HARD_BACKGROUND_MAX_WEIGHT=0.05
REGION_HARD_BACKGROUND_MAX_WEIGHT=0.12
SELECTION_PRIMARY_SOURCE=region_onset
SELECTION_MIN_PRIMARY_TOP1=0.80
SELECTION_MIN_PRIMARY_TOP2=0.95
SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT=2.0
SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT=1.5
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1=1
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2=1
EOF

tmux new-session -d -s "$SESSION_NAME" "
cd '$REPO_ROOT' &&
IFS=',' read -r -a wait_sessions <<< '$WAIT_SESSIONS' &&
for session in \"\${wait_sessions[@]}\"; do
  session=\"\${session//[[:space:]]/}\"
  while [[ -n \"\$session\" ]] && tmux list-sessions -F '#S' 2>/dev/null | grep -qx \"\$session\"; do
    echo \"[\$(date '+%F %T')] waiting for tmux session \$session\"
    sleep 300
  done
done
env \
  OUTPUT_BASE='$OUTPUT_BASE' \
  SEEDS='$SEEDS' \
  MAX_PATIENTS='$MAX_PATIENTS' \
  TOKENIZER_EPOCHS='$TOKENIZER_EPOCHS' \
  CLASSIFIER_EPOCHS='$CLASSIFIER_EPOCHS' \
  RUN_EVAL=0 \
  DEVICE='$DEVICE' \
  SKIP_EXISTING='$SKIP_EXISTING' \
  TEACHER_CACHE_DIR=outputs/tfm_soz/private_0622_fix_rows119_teacher_logits_tfm_2028_2029_2030_smoke10 \
  TEACHER_DISTILL_REGION_WEIGHT=0.25 \
  TEACHER_DISTILL_CHANNEL_WEIGHT=0.05 \
  DISABLE_REGION_BIAS_CALIBRATION=1 \
  BACKGROUND_NEGATIVE_DIR=outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives \
  BACKGROUND_NEGATIVE_RATIO=0.75 \
  BACKGROUND_NEGATIVE_SAMPLING_MODE=cluster_balanced \
  VALIDATION_BACKGROUND_NEGATIVE_DIR=outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives \
  VALIDATION_BACKGROUND_SELECTION_WEIGHT=0.75 \
  SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT=0.10 \
  CHANNEL_HARD_BACKGROUND_MAX_WEIGHT=0.05 \
  REGION_HARD_BACKGROUND_MAX_WEIGHT=0.12 \
  REGION_HARD_BACKGROUND_TARGET_WEIGHT='$REGION_HARD_BACKGROUND_TARGET_WEIGHT' \
  REGION_HARD_BACKGROUND_TARGET_REGIONS='$REGION_HARD_BACKGROUND_TARGET_REGIONS' \
  SELECTION_PRIMARY_SOURCE=region_onset \
  SELECTION_MIN_PRIMARY_TOP1=0.80 \
  SELECTION_MIN_PRIMARY_TOP2=0.95 \
  SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT=2.0 \
  SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT=1.5 \
  SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1=1 \
  SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2=1 \
  bash scripts/run_cbratfm_soz_rows119_fixedval_ensemble.sh \
  > '$OUTPUT_BASE/run.log' 2>&1
"

echo "Queued targeted hard-background smoke in tmux session: $SESSION_NAME"
echo "Output: $OUTPUT_BASE"
