#!/usr/bin/env bash
set -euo pipefail

MANIFEST="${MANIFEST:-private_sz_union_relabel_manifest_0622_fix.csv}"
PREPROCESSED_DIR="${PREPROCESSED_DIR:-outputs/tfm_soz/private_0622_fix_rows119_segments_15s}"
BACKGROUND_NEGATIVE_DIR="${BACKGROUND_NEGATIVE_DIR:-outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives}"
TEACHER_ROOTS="${TEACHER_ROOTS:-outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_regionattn_fullfast_fixedval_seed2028,outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_regionattn_fullfast_fixedval_seed2029,outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_regionattn_fullfast_fixedval_seed2030}"
TEACHER_CACHE_DIR="${TEACHER_CACHE_DIR:-outputs/tfm_soz/private_0622_fix_rows119_teacher_logits_tfm_2028_2029_2030_full43}"
OUTPUT_BASE="${OUTPUT_BASE:-outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_cbratfm_distill_topconf_fixedval}"
SEEDS="${SEEDS:-2052,2053,2054}"
SPLIT_SEED="${SPLIT_SEED:-2026}"
VAL_PATIENTS="${VAL_PATIENTS:-曾静君,李伟恺,杜克华,薛少林,陈芳}"
TOKENIZER_EPOCHS="${TOKENIZER_EPOCHS:-16}"
CLASSIFIER_EPOCHS="${CLASSIFIER_EPOCHS:-90}"
BATCH_SIZE="${BATCH_SIZE:-8}"
DEVICE="${DEVICE:-cuda}"
TEACHER_DEVICE="${TEACHER_DEVICE:-$DEVICE}"
MAX_PATIENTS="${MAX_PATIENTS:-0}"
PATIENTS="${PATIENTS:-}"
RUN_EVAL="${RUN_EVAL:-1}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"
FORCE_PREPROCESS="${FORCE_PREPROCESS:-0}"
FORCE_TEACHER_CACHE="${FORCE_TEACHER_CACHE:-0}"
WAIT_SESSIONS="${WAIT_SESSIONS:-}"
MODEL_LEVEL_GATING_CONTRACT_JSON="${MODEL_LEVEL_GATING_CONTRACT_JSON:-}"
MODEL_LEVEL_GATING_SCHEMA="${MODEL_LEVEL_GATING_SCHEMA:-}"
MODEL_LEVEL_GATING_NEGATIVE_PRIORITY="${MODEL_LEVEL_GATING_NEGATIVE_PRIORITY:-}"
MODEL_LEVEL_GATING_NON_EXECUTING="${MODEL_LEVEL_GATING_NON_EXECUTING:-0}"
SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.08}"
CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT="${CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.03}"
REGION_CLUSTER_BACKGROUND_MAX_WEIGHT="${REGION_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.10}"

if [[ -n "$WAIT_SESSIONS" ]]; then
  IFS=',' read -r -a wait_items <<< "$WAIT_SESSIONS"
  for session in "${wait_items[@]}"; do
    session="${session//[[:space:]]/}"
    while [[ -n "$session" ]] && tmux list-sessions -F '#S' 2>/dev/null | grep -qx "$session"; do
      echo "[$(date '+%F %T')] waiting for tmux session ${session}"
      sleep 300
    done
  done
fi

preprocess_needed=0
if [[ "$FORCE_PREPROCESS" == "1" || ! -f "$PREPROCESSED_DIR/index.csv" ]]; then
  preprocess_needed=1
elif [[ "$MANIFEST" -nt "$PREPROCESSED_DIR/index.csv" ]]; then
  preprocess_needed=1
elif [[ -f "$PREPROCESSED_DIR/preprocess_summary.json" && "$MANIFEST" -nt "$PREPROCESSED_DIR/preprocess_summary.json" ]]; then
  preprocess_needed=1
fi

if [[ "$preprocess_needed" == "1" ]]; then
  python3 -u code/tfm_soz/preprocess_private_tfm_soz_segments.py \
    --manifest "$MANIFEST" \
    --output-dir "$PREPROCESSED_DIR" \
    --pre-sec 5 \
    --onset-sec 5 \
    --post-sec 5
else
  echo "Using existing preprocessed data: $PREPROCESSED_DIR"
fi

expected_patients="$(python3 code/tfm_soz/list_lopo_patients.py "$PREPROCESSED_DIR" --max-patients "$MAX_PATIENTS" | wc -l | tr -d '[:space:]')"
cache_count="$(find "$TEACHER_CACHE_DIR" -maxdepth 1 -name '*.npz' 2>/dev/null | wc -l | tr -d '[:space:]')"
if [[ "$FORCE_TEACHER_CACHE" == "1" || "$cache_count" -lt "$expected_patients" ]]; then
  echo "Building teacher cache: $TEACHER_CACHE_DIR (${cache_count}/${expected_patients})"
  python3 -u code/tfm_soz/make_lopo_teacher_logit_cache.py \
    --preprocessed-dir "$PREPROCESSED_DIR" \
    --teacher-roots "$TEACHER_ROOTS" \
    --output-dir "$TEACHER_CACHE_DIR" \
    --split-seed "$SPLIT_SEED" \
    --val-patients "$VAL_PATIENTS" \
    --patients "$PATIENTS" \
    --max-patients "$MAX_PATIENTS" \
    --batch-size "$BATCH_SIZE" \
    --device "$TEACHER_DEVICE"
else
  echo "Using existing teacher cache: $TEACHER_CACHE_DIR (${cache_count}/${expected_patients})"
fi

MANIFEST="$MANIFEST" \
PREPROCESSED_DIR="$PREPROCESSED_DIR" \
OUTPUT_BASE="$OUTPUT_BASE" \
SEEDS="$SEEDS" \
SPLIT_SEED="$SPLIT_SEED" \
VAL_PATIENTS="$VAL_PATIENTS" \
TOKENIZER_EPOCHS="$TOKENIZER_EPOCHS" \
CLASSIFIER_EPOCHS="$CLASSIFIER_EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
DEVICE="$DEVICE" \
MAX_PATIENTS="$MAX_PATIENTS" \
PATIENTS="$PATIENTS" \
RUN_EVAL="$RUN_EVAL" \
SKIP_EXISTING="$SKIP_EXISTING" \
TEACHER_CACHE_DIR="$TEACHER_CACHE_DIR" \
MODEL_LEVEL_GATING_CONTRACT_JSON="$MODEL_LEVEL_GATING_CONTRACT_JSON" \
MODEL_LEVEL_GATING_SCHEMA="$MODEL_LEVEL_GATING_SCHEMA" \
MODEL_LEVEL_GATING_NEGATIVE_PRIORITY="$MODEL_LEVEL_GATING_NEGATIVE_PRIORITY" \
MODEL_LEVEL_GATING_NON_EXECUTING="$MODEL_LEVEL_GATING_NON_EXECUTING" \
TEACHER_DISTILL_REGION_WEIGHT="${TEACHER_DISTILL_REGION_WEIGHT:-0.25}" \
TEACHER_DISTILL_CHANNEL_WEIGHT="${TEACHER_DISTILL_CHANNEL_WEIGHT:-0.05}" \
TEACHER_DISTILL_TEMPERATURE="${TEACHER_DISTILL_TEMPERATURE:-2.0}" \
REGION_POSITIVE_SET_MARGIN_WEIGHT="${REGION_POSITIVE_SET_MARGIN_WEIGHT:-0.25}" \
SEGMENT_EVENTNESS_LOSS_WEIGHT="${SEGMENT_EVENTNESS_LOSS_WEIGHT:-0.10}" \
SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT="${SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT:-0.10}" \
SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT:-0.05}" \
SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT:-0.10}" \
SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT="$SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT" \
CHANNEL_BACKGROUND_MAX_WEIGHT="${CHANNEL_BACKGROUND_MAX_WEIGHT:-0.02}" \
CHANNEL_HARD_BACKGROUND_MAX_WEIGHT="${CHANNEL_HARD_BACKGROUND_MAX_WEIGHT:-0.05}" \
CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT="$CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT" \
REGION_BACKGROUND_MAX_WEIGHT="${REGION_BACKGROUND_MAX_WEIGHT:-0.05}" \
REGION_HARD_BACKGROUND_MAX_WEIGHT="${REGION_HARD_BACKGROUND_MAX_WEIGHT:-0.12}" \
REGION_HARD_BACKGROUND_TARGET_WEIGHT="${REGION_HARD_BACKGROUND_TARGET_WEIGHT:-0.05}" \
REGION_HARD_BACKGROUND_TARGET_REGIONS="${REGION_HARD_BACKGROUND_TARGET_REGIONS:-right_temporal,left_temporal}" \
REGION_CLUSTER_BACKGROUND_MAX_WEIGHT="$REGION_CLUSTER_BACKGROUND_MAX_WEIGHT" \
BACKGROUND_NEGATIVE_DIR="$BACKGROUND_NEGATIVE_DIR" \
BACKGROUND_NEGATIVE_RATIO="${BACKGROUND_NEGATIVE_RATIO:-0.75}" \
BACKGROUND_NEGATIVE_SAMPLING_MODE="${BACKGROUND_NEGATIVE_SAMPLING_MODE:-cluster_balanced}" \
VALIDATION_BACKGROUND_NEGATIVE_DIR="${VALIDATION_BACKGROUND_NEGATIVE_DIR:-$BACKGROUND_NEGATIVE_DIR}" \
VALIDATION_BACKGROUND_SELECTION_WEIGHT="${VALIDATION_BACKGROUND_SELECTION_WEIGHT:-0.75}" \
USE_CONTEXT_DELTA_HEADS="${USE_CONTEXT_DELTA_HEADS:-1}" \
USE_CBRAMOD_RESIDUAL_BRANCH="${USE_CBRAMOD_RESIDUAL_BRANCH:-1}" \
CBRAMOD_RESIDUAL_INIT="${CBRAMOD_RESIDUAL_INIT:--4.0}" \
USE_CBRAMOD_CRISS_CROSS="${USE_CBRAMOD_CRISS_CROSS:-0}" \
SELECTION_PRIMARY_SOURCE="${SELECTION_PRIMARY_SOURCE:-region_onset}" \
SELECTION_MIN_PRIMARY_TOP1="${SELECTION_MIN_PRIMARY_TOP1:-0.80}" \
SELECTION_MIN_PRIMARY_TOP2="${SELECTION_MIN_PRIMARY_TOP2:-0.95}" \
SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT="${SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT:-2.0}" \
SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT="${SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT:-1.5}" \
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1="${SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1:-1}" \
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2="${SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2:-1}" \
scripts/run_cbratfm_soz_rows119_fixedval_ensemble.sh
