#!/usr/bin/env bash
set -euo pipefail

# Strict eventness/background LOPO recipe for the corrected private SOZ labels.
#
# Label rule:
# - pre   [sz_start-5, sz_start): all channels/regions are negative
# - onset [sz_start, sz_start+5): only soz_bipolar-derived SOZ channels/regions are positive
# - post  [sz_start+5, sz_start+10): all channels/regions are negative
#
# Leakage rule:
# - held-out patient is never used for training
# - background negatives mixed into training are filtered to train patients by
#   train_private_soz_segments.py
# - validation-patient background negatives are used only for checkpoint
#   selection penalties, never as training samples
# - continuous thresholds/eventness gates are selected on validation files only
#
# Eventness losses:
# - BCE labels onset segments as positive only when soz_bipolar-derived SOZ is present
# - onset-vs-context ranking pushes onset eventness above pre/post context
# - background-max suppresses the strongest segment eventness in all-zero windows

PREPROCESSED_DIR="${PREPROCESSED_DIR:-outputs/tfm_soz/private_0622_fix_rows119_segments_15s}"
BACKGROUND_NEGATIVE_DIR="${BACKGROUND_NEGATIVE_DIR:-outputs/tfm_soz/private_0622_fix_rows119_segments_15s_background_negatives}"
OUTPUT_ROOT="${OUTPUT_ROOT:-outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_eventness_bg_seed2036}"
CONTINUOUS_OUTPUT="${CONTINUOUS_OUTPUT:-outputs/tfm_soz/private_0622_fix_rows119_continuous_fullfile/eventness_bg_seed2036_allfiles_file1_fpr10_gate_step10_fullfile.json}"

SEED="${SEED:-2036}"
SPLIT_SEED="${SPLIT_SEED:-2028}"
VAL_PATIENTS="${VAL_PATIENTS:-曾静君,李伟恺,杜克华,薛少林,陈芳}"
PATIENTS="${PATIENTS:-}"
MAX_PATIENTS="${MAX_PATIENTS:-0}"
DEVICE="${DEVICE:-cuda}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"

TOKENIZER_EPOCHS="${TOKENIZER_EPOCHS:-16}"
CLASSIFIER_EPOCHS="${CLASSIFIER_EPOCHS:-90}"
BATCH_SIZE="${BATCH_SIZE:-8}"

BACKGROUND_WINDOWS_PER_FILE="${BACKGROUND_WINDOWS_PER_FILE:-3}"
BACKGROUND_MAX_WINDOWS_PER_PATIENT="${BACKGROUND_MAX_WINDOWS_PER_PATIENT:-30}"
BACKGROUND_CANDIDATE_STRIDE_SEC="${BACKGROUND_CANDIDATE_STRIDE_SEC:-15}"
BACKGROUND_EXCLUDE_PRE_SEC="${BACKGROUND_EXCLUDE_PRE_SEC:-30}"
BACKGROUND_EXCLUDE_POST_SEC="${BACKGROUND_EXCLUDE_POST_SEC:-30}"
FORCE_PREPROCESS="${FORCE_PREPROCESS:-0}"
FORCE_BACKGROUND_PREPROCESS="${FORCE_BACKGROUND_PREPROCESS:-0}"

BACKGROUND_NEGATIVE_RATIO="${BACKGROUND_NEGATIVE_RATIO:-1.0}"
BACKGROUND_NEGATIVE_MAX_SAMPLES="${BACKGROUND_NEGATIVE_MAX_SAMPLES:-0}"
BACKGROUND_NEGATIVE_SEED="${BACKGROUND_NEGATIVE_SEED:-$SEED}"
VALIDATION_BACKGROUND_MAX_SAMPLES="${VALIDATION_BACKGROUND_MAX_SAMPLES:-0}"
VALIDATION_BACKGROUND_SEED="${VALIDATION_BACKGROUND_SEED:-$SEED}"
VALIDATION_BACKGROUND_SELECTION_WEIGHT="${VALIDATION_BACKGROUND_SELECTION_WEIGHT:-0.75}"

SEGMENT_EVENTNESS_LOSS_WEIGHT="${SEGMENT_EVENTNESS_LOSS_WEIGHT:-0.5}"
SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT="${SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT:-0.3}"
SEGMENT_EVENTNESS_CONTRASTIVE_MARGIN="${SEGMENT_EVENTNESS_CONTRASTIVE_MARGIN:-0.2}"
SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT:-0.3}"
CHANNEL_BACKGROUND_MAX_WEIGHT="${CHANNEL_BACKGROUND_MAX_WEIGHT:-0.1}"
REGION_BACKGROUND_MAX_WEIGHT="${REGION_BACKGROUND_MAX_WEIGHT:-0.3}"
USE_CONTEXT_DELTA_HEADS="${USE_CONTEXT_DELTA_HEADS:-1}"
USE_REGION_ATTENTION_POOLING="${USE_REGION_ATTENTION_POOLING:-1}"
USE_REGION_EMBEDDING_HEAD="${USE_REGION_EMBEDDING_HEAD:-1}"

AUGMENT_NOISE_STD="${AUGMENT_NOISE_STD:-0.03}"
AUGMENT_SCALE_STD="${AUGMENT_SCALE_STD:-0.08}"
AUGMENT_SEGMENT_RECONSTRUCT_PROB="${AUGMENT_SEGMENT_RECONSTRUCT_PROB:-0.2}"
AUGMENT_SEGMENT_RECONSTRUCT_PIECES="${AUGMENT_SEGMENT_RECONSTRUCT_PIECES:-4}"
AUGMENT_NEGATIVE_CHANNEL_DROP_PROB="${AUGMENT_NEGATIVE_CHANNEL_DROP_PROB:-0.2}"
AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION="${AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION:-0.25}"
AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB="${AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB:-0.2}"
AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC="${AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC:-0.5}"

RUN_CONTINUOUS_EVAL="${RUN_CONTINUOUS_EVAL:-1}"
MAX_TEST_FILES="${MAX_TEST_FILES:-1}"
MAX_VAL_FILES="${MAX_VAL_FILES:-1}"
STEP_SEC="${STEP_SEC:-10}"
WINDOW_CHUNK_SIZE="${WINDOW_CHUNK_SIZE:-128}"
READ_WINDOW_CHUNK_SIZE="${READ_WINDOW_CHUNK_SIZE:-64}"
TARGET_FPR_PER_HOUR="${TARGET_FPR_PER_HOUR:-10}"
MIN_SENSITIVITY="${MIN_SENSITIVITY:-0.8}"
MAX_NEGATIVE_ALARM_RATE="${MAX_NEGATIVE_ALARM_RATE:-0.25}"
CONTINUOUS_THRESHOLD_POLICY="${CONTINUOUS_THRESHOLD_POLICY:-fpr_target}"
EVENTNESS_SCORE_COLUMN="${EVENTNESS_SCORE_COLUMN:-onset_eventness_score}"
EVENTNESS_GRID_MODE="${EVENTNESS_GRID_MODE:-linspace}"

if [[ "$FORCE_PREPROCESS" == "1" || ! -f "$PREPROCESSED_DIR/index.csv" ]]; then
  python3 -u code/tfm_soz/preprocess_private_tfm_soz_segments.py \
    --manifest private_sz_union_relabel_manifest_0622_fix.csv \
    --output-dir "$PREPROCESSED_DIR" \
    --pre-sec 5 \
    --onset-sec 5 \
    --post-sec 5
else
  echo "Using existing preprocessed event data: $PREPROCESSED_DIR"
fi

if [[ "$FORCE_BACKGROUND_PREPROCESS" == "1" || ! -f "$BACKGROUND_NEGATIVE_DIR/index.csv" ]]; then
  python3 -u code/tfm_soz/preprocess_private_tfm_soz_background_negatives.py \
    --source-dir "$PREPROCESSED_DIR" \
    --output-dir "$BACKGROUND_NEGATIVE_DIR" \
    --windows-per-file "$BACKGROUND_WINDOWS_PER_FILE" \
    --max-windows-per-patient "$BACKGROUND_MAX_WINDOWS_PER_PATIENT" \
    --candidate-stride-sec "$BACKGROUND_CANDIDATE_STRIDE_SEC" \
    --exclude-pre-sec "$BACKGROUND_EXCLUDE_PRE_SEC" \
    --exclude-post-sec "$BACKGROUND_EXCLUDE_POST_SEC" \
    --seed "$SEED"
else
  echo "Using existing background negatives: $BACKGROUND_NEGATIVE_DIR"
fi

PREPROCESSED_DIR="$PREPROCESSED_DIR" \
OUTPUT_ROOT="$OUTPUT_ROOT" \
TOKENIZER_EPOCHS="$TOKENIZER_EPOCHS" \
CLASSIFIER_EPOCHS="$CLASSIFIER_EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
SEED="$SEED" \
SPLIT_SEED="$SPLIT_SEED" \
VAL_PATIENTS="$VAL_PATIENTS" \
PATIENTS="$PATIENTS" \
MAX_PATIENTS="$MAX_PATIENTS" \
SKIP_EXISTING="$SKIP_EXISTING" \
USE_SEGMENT_EVENTNESS_HEAD=1 \
SEGMENT_EVENTNESS_LOSS_WEIGHT="$SEGMENT_EVENTNESS_LOSS_WEIGHT" \
SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT="$SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT" \
SEGMENT_EVENTNESS_CONTRASTIVE_MARGIN="$SEGMENT_EVENTNESS_CONTRASTIVE_MARGIN" \
SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT="$SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT" \
CHANNEL_BACKGROUND_MAX_WEIGHT="$CHANNEL_BACKGROUND_MAX_WEIGHT" \
REGION_BACKGROUND_MAX_WEIGHT="$REGION_BACKGROUND_MAX_WEIGHT" \
USE_CONTEXT_DELTA_HEADS="$USE_CONTEXT_DELTA_HEADS" \
USE_REGION_ATTENTION_POOLING="$USE_REGION_ATTENTION_POOLING" \
USE_REGION_EMBEDDING_HEAD="$USE_REGION_EMBEDDING_HEAD" \
BACKGROUND_NEGATIVE_DIR="$BACKGROUND_NEGATIVE_DIR" \
BACKGROUND_NEGATIVE_RATIO="$BACKGROUND_NEGATIVE_RATIO" \
BACKGROUND_NEGATIVE_MAX_SAMPLES="$BACKGROUND_NEGATIVE_MAX_SAMPLES" \
BACKGROUND_NEGATIVE_SEED="$BACKGROUND_NEGATIVE_SEED" \
VALIDATION_BACKGROUND_NEGATIVE_DIR="$BACKGROUND_NEGATIVE_DIR" \
VALIDATION_BACKGROUND_MAX_SAMPLES="$VALIDATION_BACKGROUND_MAX_SAMPLES" \
VALIDATION_BACKGROUND_SEED="$VALIDATION_BACKGROUND_SEED" \
VALIDATION_BACKGROUND_SELECTION_WEIGHT="$VALIDATION_BACKGROUND_SELECTION_WEIGHT" \
AUGMENT_NOISE_STD="$AUGMENT_NOISE_STD" \
AUGMENT_SCALE_STD="$AUGMENT_SCALE_STD" \
AUGMENT_SEGMENT_RECONSTRUCT_PROB="$AUGMENT_SEGMENT_RECONSTRUCT_PROB" \
AUGMENT_SEGMENT_RECONSTRUCT_PIECES="$AUGMENT_SEGMENT_RECONSTRUCT_PIECES" \
AUGMENT_NEGATIVE_CHANNEL_DROP_PROB="$AUGMENT_NEGATIVE_CHANNEL_DROP_PROB" \
AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION="$AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION" \
AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB="$AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB" \
AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC="$AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC" \
scripts/run_tfm_soz_private_segments_lopo.sh

if [[ "$RUN_CONTINUOUS_EVAL" != "1" ]]; then
  exit 0
fi

python3 -u code/tfm_soz/evaluate_lopo_continuous_fullfile.py \
  --lopo-root "$OUTPUT_ROOT" \
  --preprocessed-dir "$PREPROCESSED_DIR" \
  --output "$CONTINUOUS_OUTPUT" \
  --threshold-policy "$CONTINUOUS_THRESHOLD_POLICY" \
  --target-fpr-per-hour "$TARGET_FPR_PER_HOUR" \
  --min-sensitivity "$MIN_SENSITIVITY" \
  --max-negative-alarm-rate "$MAX_NEGATIVE_ALARM_RATE" \
  --use-eventness-gate \
  --eventness-score-column "$EVENTNESS_SCORE_COLUMN" \
  --eventness-grid-mode "$EVENTNESS_GRID_MODE" \
  --event-time-policy causal_end \
  --max-test-files "$MAX_TEST_FILES" \
  --max-val-files "$MAX_VAL_FILES" \
  --step-sec "$STEP_SEC" \
  --batch-size "$BATCH_SIZE" \
  --window-chunk-size "$WINDOW_CHUNK_SIZE" \
  --read-window-chunk-size "$READ_WINDOW_CHUNK_SIZE" \
  --device "$DEVICE" \
  --quiet
