#!/usr/bin/env bash
set -euo pipefail

PREPROCESSED_DIR="${PREPROCESSED_DIR:-outputs/tfm_soz/private_0622_fix_rows119_segments_15s}"
MANIFEST="${MANIFEST:-private_sz_union_relabel_manifest_0622_fix.csv}"
OUTPUT_BASE="${OUTPUT_BASE:-outputs/tfm_soz/private_0622_fix_rows119_segment_lopo_cbratfm_fixedval}"
PRE_SEC="${PRE_SEC:-5}"
ONSET_SEC="${ONSET_SEC:-5}"
POST_SEC="${POST_SEC:-5}"
SEEDS="${SEEDS:-2041,2042,2043}"
SPLIT_SEED="${SPLIT_SEED:-2026}"
VAL_PATIENTS="${VAL_PATIENTS:-曾静君,李伟恺,杜克华,薛少林,陈芳}"
TOKENIZER_EPOCHS="${TOKENIZER_EPOCHS:-12}"
CLASSIFIER_EPOCHS="${CLASSIFIER_EPOCHS:-60}"
BATCH_SIZE="${BATCH_SIZE:-8}"
DEVICE="${DEVICE:-cuda}"
MAX_PATIENTS="${MAX_PATIENTS:-0}"
PATIENTS="${PATIENTS:-}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"
RUN_EVAL="${RUN_EVAL:-1}"
BOOTSTRAP_ITERS="${BOOTSTRAP_ITERS:-2000}"

# SOZ localization losses.
HARD_NEGATIVE_FRACTION="${HARD_NEGATIVE_FRACTION:-0.25}"
CHANNEL_HARD_NEGATIVE_WEIGHT="${CHANNEL_HARD_NEGATIVE_WEIGHT:-0.05}"
REGION_HARD_NEGATIVE_WEIGHT="${REGION_HARD_NEGATIVE_WEIGHT:-0.25}"
CHANNEL_POSITIVE_SET_MARGIN_WEIGHT="${CHANNEL_POSITIVE_SET_MARGIN_WEIGHT:-0.0}"
REGION_POSITIVE_SET_MARGIN_WEIGHT="${REGION_POSITIVE_SET_MARGIN_WEIGHT:-0.25}"
POSITIVE_SET_MARGIN="${POSITIVE_SET_MARGIN:-0.2}"

# Onset/context eventness and background suppression.
SEGMENT_EVENTNESS_LOSS_WEIGHT="${SEGMENT_EVENTNESS_LOSS_WEIGHT:-0.10}"
SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT="${SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT:-0.10}"
SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT:-0.05}"
SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT:-0.0}"
SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT="${SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.0}"
CHANNEL_BACKGROUND_MAX_WEIGHT="${CHANNEL_BACKGROUND_MAX_WEIGHT:-0.02}"
CHANNEL_HARD_BACKGROUND_MAX_WEIGHT="${CHANNEL_HARD_BACKGROUND_MAX_WEIGHT:-0.0}"
CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT="${CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.0}"
REGION_BACKGROUND_MAX_WEIGHT="${REGION_BACKGROUND_MAX_WEIGHT:-0.05}"
REGION_HARD_BACKGROUND_MAX_WEIGHT="${REGION_HARD_BACKGROUND_MAX_WEIGHT:-0.0}"
REGION_HARD_BACKGROUND_TARGET_WEIGHT="${REGION_HARD_BACKGROUND_TARGET_WEIGHT:-0.0}"
REGION_HARD_BACKGROUND_TARGET_REGIONS="${REGION_HARD_BACKGROUND_TARGET_REGIONS:-}"
REGION_CLUSTER_BACKGROUND_MAX_WEIGHT="${REGION_CLUSTER_BACKGROUND_MAX_WEIGHT:-0.0}"
USE_CONTEXT_DELTA_HEADS="${USE_CONTEXT_DELTA_HEADS:-0}"
BACKGROUND_NEGATIVE_DIR="${BACKGROUND_NEGATIVE_DIR:-}"
BACKGROUND_NEGATIVE_RATIO="${BACKGROUND_NEGATIVE_RATIO:-0}"
BACKGROUND_NEGATIVE_MAX_SAMPLES="${BACKGROUND_NEGATIVE_MAX_SAMPLES:-0}"
BACKGROUND_NEGATIVE_SEED="${BACKGROUND_NEGATIVE_SEED:--1}"
BACKGROUND_NEGATIVE_SAMPLING_MODE="${BACKGROUND_NEGATIVE_SAMPLING_MODE:-random}"
VALIDATION_BACKGROUND_NEGATIVE_DIR="${VALIDATION_BACKGROUND_NEGATIVE_DIR:-}"
VALIDATION_BACKGROUND_MAX_SAMPLES="${VALIDATION_BACKGROUND_MAX_SAMPLES:-0}"
VALIDATION_BACKGROUND_SEED="${VALIDATION_BACKGROUND_SEED:--1}"
VALIDATION_BACKGROUND_SELECTION_WEIGHT="${VALIDATION_BACKGROUND_SELECTION_WEIGHT:-0}"
SELECTION_PRIMARY_SOURCE="${SELECTION_PRIMARY_SOURCE:-auto}"
SELECTION_MIN_PRIMARY_TOP1="${SELECTION_MIN_PRIMARY_TOP1:-0}"
SELECTION_MIN_PRIMARY_TOP2="${SELECTION_MIN_PRIMARY_TOP2:-0}"
SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT="${SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT:-0}"
SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT="${SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT:-0}"
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1="${SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1:-0}"
SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2="${SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2:-0}"
TEACHER_CACHE_DIR="${TEACHER_CACHE_DIR:-}"
TEACHER_DISTILL_REGION_WEIGHT="${TEACHER_DISTILL_REGION_WEIGHT:-0}"
TEACHER_DISTILL_CHANNEL_WEIGHT="${TEACHER_DISTILL_CHANNEL_WEIGHT:-0}"
TEACHER_DISTILL_TEMPERATURE="${TEACHER_DISTILL_TEMPERATURE:-2.0}"
MODEL_LEVEL_GATING_CONTRACT_JSON="${MODEL_LEVEL_GATING_CONTRACT_JSON:-}"
MODEL_LEVEL_GATING_SCHEMA="${MODEL_LEVEL_GATING_SCHEMA:-}"
MODEL_LEVEL_GATING_NEGATIVE_PRIORITY="${MODEL_LEVEL_GATING_NEGATIVE_PRIORITY:-}"
MODEL_LEVEL_GATING_NON_EXECUTING="${MODEL_LEVEL_GATING_NON_EXECUTING:-0}"
USE_CBRAMOD_CRISS_CROSS="${USE_CBRAMOD_CRISS_CROSS:-0}"
USE_CBRAMOD_RESIDUAL_BRANCH="${USE_CBRAMOD_RESIDUAL_BRANCH:-1}"
CBRAMOD_RESIDUAL_INIT="${CBRAMOD_RESIDUAL_INIT:--4.0}"
USE_HIERARCHICAL_SET_RESIDUAL="${USE_HIERARCHICAL_SET_RESIDUAL:-0}"
HIERARCHICAL_SET_RESIDUAL_INIT="${HIERARCHICAL_SET_RESIDUAL_INIT:-0.0}"
INIT_LOPO_ROOT="${INIT_LOPO_ROOT:-}"
DISABLE_REGION_BIAS_CALIBRATION="${DISABLE_REGION_BIAS_CALIBRATION:-0}"

# Label-preserving augmentation for small private cohorts.
AUGMENT_NOISE_STD="${AUGMENT_NOISE_STD:-0.03}"
AUGMENT_SCALE_STD="${AUGMENT_SCALE_STD:-0.08}"
AUGMENT_NEGATIVE_CHANNEL_DROP_PROB="${AUGMENT_NEGATIVE_CHANNEL_DROP_PROB:-0.15}"
AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION="${AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION:-0.25}"
AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB="${AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB:-0.15}"
AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC="${AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC:-0.5}"
AUGMENT_SEGMENT_RECONSTRUCT_PROB="${AUGMENT_SEGMENT_RECONSTRUCT_PROB:-0.0}"
AUGMENT_FREQUENCY_MASK_PROB="${AUGMENT_FREQUENCY_MASK_PROB:-0.0}"
AUGMENT_FREQUENCY_MASK_MAX_FRACTION="${AUGMENT_FREQUENCY_MASK_MAX_FRACTION:-0.08}"

preprocess_needed=0
if [[ ! -f "$PREPROCESSED_DIR/index.csv" ]]; then
  preprocess_needed=1
elif [[ "$MANIFEST" -nt "$PREPROCESSED_DIR/index.csv" ]]; then
  preprocess_needed=1
elif [[ -f "$PREPROCESSED_DIR/preprocess_summary.json" && "$MANIFEST" -nt "$PREPROCESSED_DIR/preprocess_summary.json" ]]; then
  preprocess_needed=1
fi

if [[ "$preprocess_needed" == "1" ]]; then
  python3 -u code/tfm_soz/preprocess_private_tfm_soz_segments.py \
    --manifest "$MANIFEST" \
    --output-dir "$PREPROCESSED_DIR" \
    --pre-sec "$PRE_SEC" \
    --onset-sec "$ONSET_SEC" \
    --post-sec "$POST_SEC"
fi

IFS=',' read -r -a SEED_ITEMS <<< "$SEEDS"
ROOTS=()
for seed in "${SEED_ITEMS[@]}"; do
  seed="${seed//[[:space:]]/}"
  if [[ -z "$seed" ]]; then
    continue
  fi
  root="${OUTPUT_BASE}_seed${seed}"
  ROOTS+=("$root")
  echo "== CBraTFM-SOZ rows119 LOPO seed ${seed}: ${root} =="
  PREPROCESSED_DIR="$PREPROCESSED_DIR" \
  MANIFEST="$MANIFEST" \
  PRE_SEC="$PRE_SEC" \
  ONSET_SEC="$ONSET_SEC" \
  POST_SEC="$POST_SEC" \
  OUTPUT_ROOT="$root" \
  TOKENIZER_EPOCHS="$TOKENIZER_EPOCHS" \
  CLASSIFIER_EPOCHS="$CLASSIFIER_EPOCHS" \
  BATCH_SIZE="$BATCH_SIZE" \
  SEED="$seed" \
  SPLIT_SEED="$SPLIT_SEED" \
  VAL_PATIENTS="$VAL_PATIENTS" \
  MAX_PATIENTS="$MAX_PATIENTS" \
  PATIENTS="$PATIENTS" \
  SKIP_EXISTING="$SKIP_EXISTING" \
  DEVICE="$DEVICE" \
  HARD_NEGATIVE_FRACTION="$HARD_NEGATIVE_FRACTION" \
  CHANNEL_HARD_NEGATIVE_WEIGHT="$CHANNEL_HARD_NEGATIVE_WEIGHT" \
  REGION_HARD_NEGATIVE_WEIGHT="$REGION_HARD_NEGATIVE_WEIGHT" \
  CHANNEL_POSITIVE_SET_MARGIN_WEIGHT="$CHANNEL_POSITIVE_SET_MARGIN_WEIGHT" \
  REGION_POSITIVE_SET_MARGIN_WEIGHT="$REGION_POSITIVE_SET_MARGIN_WEIGHT" \
  POSITIVE_SET_MARGIN="$POSITIVE_SET_MARGIN" \
  USE_SEGMENT_EVENTNESS_HEAD=1 \
  SEGMENT_EVENTNESS_LOSS_WEIGHT="$SEGMENT_EVENTNESS_LOSS_WEIGHT" \
  SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT="$SEGMENT_EVENTNESS_CONTRASTIVE_WEIGHT" \
  SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT="$SEGMENT_EVENTNESS_BACKGROUND_MAX_WEIGHT" \
  SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT="$SEGMENT_EVENTNESS_HARD_BACKGROUND_MAX_WEIGHT" \
  SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT="$SEGMENT_EVENTNESS_CLUSTER_BACKGROUND_MAX_WEIGHT" \
  CHANNEL_BACKGROUND_MAX_WEIGHT="$CHANNEL_BACKGROUND_MAX_WEIGHT" \
  CHANNEL_HARD_BACKGROUND_MAX_WEIGHT="$CHANNEL_HARD_BACKGROUND_MAX_WEIGHT" \
  CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT="$CHANNEL_CLUSTER_BACKGROUND_MAX_WEIGHT" \
  REGION_BACKGROUND_MAX_WEIGHT="$REGION_BACKGROUND_MAX_WEIGHT" \
  REGION_HARD_BACKGROUND_MAX_WEIGHT="$REGION_HARD_BACKGROUND_MAX_WEIGHT" \
  REGION_HARD_BACKGROUND_TARGET_WEIGHT="$REGION_HARD_BACKGROUND_TARGET_WEIGHT" \
  REGION_HARD_BACKGROUND_TARGET_REGIONS="$REGION_HARD_BACKGROUND_TARGET_REGIONS" \
  REGION_CLUSTER_BACKGROUND_MAX_WEIGHT="$REGION_CLUSTER_BACKGROUND_MAX_WEIGHT" \
  USE_CONTEXT_DELTA_HEADS="$USE_CONTEXT_DELTA_HEADS" \
  BACKGROUND_NEGATIVE_DIR="$BACKGROUND_NEGATIVE_DIR" \
  BACKGROUND_NEGATIVE_RATIO="$BACKGROUND_NEGATIVE_RATIO" \
  BACKGROUND_NEGATIVE_MAX_SAMPLES="$BACKGROUND_NEGATIVE_MAX_SAMPLES" \
  BACKGROUND_NEGATIVE_SEED="$BACKGROUND_NEGATIVE_SEED" \
  BACKGROUND_NEGATIVE_SAMPLING_MODE="$BACKGROUND_NEGATIVE_SAMPLING_MODE" \
  VALIDATION_BACKGROUND_NEGATIVE_DIR="$VALIDATION_BACKGROUND_NEGATIVE_DIR" \
  VALIDATION_BACKGROUND_MAX_SAMPLES="$VALIDATION_BACKGROUND_MAX_SAMPLES" \
  VALIDATION_BACKGROUND_SEED="$VALIDATION_BACKGROUND_SEED" \
  VALIDATION_BACKGROUND_SELECTION_WEIGHT="$VALIDATION_BACKGROUND_SELECTION_WEIGHT" \
  SELECTION_PRIMARY_SOURCE="$SELECTION_PRIMARY_SOURCE" \
  SELECTION_MIN_PRIMARY_TOP1="$SELECTION_MIN_PRIMARY_TOP1" \
  SELECTION_MIN_PRIMARY_TOP2="$SELECTION_MIN_PRIMARY_TOP2" \
  SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT="$SELECTION_PRIMARY_TOP1_PENALTY_WEIGHT" \
  SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT="$SELECTION_PRIMARY_TOP2_PENALTY_WEIGHT" \
  SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1="$SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP1" \
  SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2="$SELECTION_BACKGROUND_REQUIRES_PRIMARY_TOP2" \
  TEACHER_CACHE_DIR="$TEACHER_CACHE_DIR" \
  TEACHER_DISTILL_REGION_WEIGHT="$TEACHER_DISTILL_REGION_WEIGHT" \
  TEACHER_DISTILL_CHANNEL_WEIGHT="$TEACHER_DISTILL_CHANNEL_WEIGHT" \
  TEACHER_DISTILL_TEMPERATURE="$TEACHER_DISTILL_TEMPERATURE" \
  MODEL_LEVEL_GATING_CONTRACT_JSON="$MODEL_LEVEL_GATING_CONTRACT_JSON" \
  MODEL_LEVEL_GATING_SCHEMA="$MODEL_LEVEL_GATING_SCHEMA" \
  MODEL_LEVEL_GATING_NEGATIVE_PRIORITY="$MODEL_LEVEL_GATING_NEGATIVE_PRIORITY" \
  MODEL_LEVEL_GATING_NON_EXECUTING="$MODEL_LEVEL_GATING_NON_EXECUTING" \
  AUGMENT_NOISE_STD="$AUGMENT_NOISE_STD" \
  AUGMENT_SCALE_STD="$AUGMENT_SCALE_STD" \
  AUGMENT_NEGATIVE_CHANNEL_DROP_PROB="$AUGMENT_NEGATIVE_CHANNEL_DROP_PROB" \
  AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION="$AUGMENT_NEGATIVE_CHANNEL_DROP_MAX_FRACTION" \
  AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB="$AUGMENT_LABEL_PRESERVING_TIME_MASK_PROB" \
  AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC="$AUGMENT_LABEL_PRESERVING_TIME_MASK_MAX_SEC" \
  AUGMENT_SEGMENT_RECONSTRUCT_PROB="$AUGMENT_SEGMENT_RECONSTRUCT_PROB" \
  AUGMENT_FREQUENCY_MASK_PROB="$AUGMENT_FREQUENCY_MASK_PROB" \
  AUGMENT_FREQUENCY_MASK_MAX_FRACTION="$AUGMENT_FREQUENCY_MASK_MAX_FRACTION" \
  USE_CBRAMOD_CRISS_CROSS="$USE_CBRAMOD_CRISS_CROSS" \
  USE_CBRAMOD_RESIDUAL_BRANCH="$USE_CBRAMOD_RESIDUAL_BRANCH" \
  CBRAMOD_RESIDUAL_INIT="$CBRAMOD_RESIDUAL_INIT" \
  USE_HIERARCHICAL_SET_RESIDUAL="$USE_HIERARCHICAL_SET_RESIDUAL" \
  HIERARCHICAL_SET_RESIDUAL_INIT="$HIERARCHICAL_SET_RESIDUAL_INIT" \
  INIT_LOPO_ROOT="$INIT_LOPO_ROOT" \
  DISABLE_REGION_BIAS_CALIBRATION="$DISABLE_REGION_BIAS_CALIBRATION" \
  USE_REGION_ATTENTION_POOLING=1 \
  USE_REGION_EMBEDDING_HEAD=1 \
  scripts/run_tfm_soz_private_segments_lopo.sh
done

if [[ "$RUN_EVAL" != "1" ]]; then
  exit 0
fi

mkdir -p "$OUTPUT_BASE"
roots_csv="$(IFS=,; echo "${ROOTS[*]}")"

python3 code/tfm_soz/evaluate_lopo_global_fusion.py \
  --roots "$roots_csv" \
  --output "$OUTPUT_BASE/lopo_test_global_fusion_equal.json" \
  --objective top1 \
  --alpha-grid-step 0.01

python3 code/tfm_soz/evaluate_lopo_ensemble_operating_points.py \
  --roots "$roots_csv" \
  --output "$OUTPUT_BASE/lopo_test_global_equal_operating_points.json" \
  --fusion-mode global \
  --seed-weight-mode equal \
  --ensemble-objective top1 \
  --alpha-grid-step 0.01 \
  --policy-objectives f1,balanced,low_fpr,low_fnr

python3 code/tfm_soz/evaluate_lopo_ensemble_operating_points.py \
  --roots "$roots_csv" \
  --output "$OUTPUT_BASE/lopo_test_global_equal_top1_augmented_operating_points.json" \
  --fusion-mode global \
  --seed-weight-mode equal \
  --ensemble-objective top1 \
  --alpha-grid-step 0.01 \
  --policy-objectives f1,balanced,low_fpr,low_fnr \
  --policy-family top1_augmented

python3 code/tfm_soz/evaluate_lopo_ensemble_constrained_policies.py \
  --roots "$roots_csv" \
  --output "$OUTPUT_BASE/lopo_test_global_equal_top1_augmented_constrained_policies.json" \
  --fusion-mode global \
  --seed-weight-mode equal \
  --ensemble-objective top1 \
  --alpha-grid-step 0.01 \
  --policy-family top1_augmented

python3 code/tfm_soz/evaluate_lopo_ensemble_bootstrap.py \
  --roots "$roots_csv" \
  --output "$OUTPUT_BASE/lopo_test_global_equal_bootstrap_ci.json" \
  --fusion-mode global \
  --seed-weight-mode equal \
  --ensemble-objective top1 \
  --alpha-grid-step 0.01 \
  --bootstrap-iters "$BOOTSTRAP_ITERS"
